### PR TITLE
Log payload of unretryable status codes

### PR DESCRIPTION
**Pull request by linkous8**
- Add missing servo import
- Set unretryable log level to error
- Add error response to log
- Add .vscode to project for auto linting with black and other useful
settings

### CODE REVIEW

**Review by pavel-georgiev — COMMENTED** [review]
What is the output when there is a >500 error? 

Also - is this safe for the case when the error has no payload?

**Comment by linkous8** [comment]
> What is the output when there is a >500 error?

The response object is appended to the current log message as a pretty formatted string: https://docs.python.org/3/library/pprint.html#pprint.pformat


> Also - is this safe for the case when the error has no payload?

There is no increased risk over the current implementation. If you have a clearly documented safety concern then please raise a new issue for triage

**Review by pavel-georgiev — CHANGES_REQUESTED** [review]
Fred, this has the following issues that are not as specified in ENG-790:
1. The error payload for < 500 codes in not logged. Instead you get a dump of the `requests` response object, i.e. `<Response [400 Bad Request]>`, which is not helpful. The intent of this change is to log the payload. Also (I tried to hint that in my original note) - when logging the response body, make sure it can work with an empty payload
2. There is no response logging at all for errors >= 500 

As a general note - please test these changes before submitting a fix for review. If you need a way to simulate OCO responding with an error, see the original issue description (ENG-754), the issue is easily reproducible. If you want to have OCO return > 500 instead of 400 (for testing purposes), please see [this](https://github.com/opsani/oco/commit/4eef26fd8af2b2b945c8572361f4c433008b132b) OCO branch

**Comment by linkous8** [comment]
> 1. The error payload for < 500 codes in not logged. Instead you get a dump of the `requests` response object, i.e. `<Response [400 Bad Request]>`, which is not helpful. The intent of this change is to log the payload. Also (I tried to hint that in my original note) - when logging the response body, make sure it can work with an empty payload

My bad, NMF these web libraries make it so difficult to dump the entire response content. You'd think devtools would work properly here...

> 2. There is no response logging at all for errors >= 500

* https://github.com/opsani/servox/blob/6901d5f76cb886a8f11c5682c6401e139c3303a9/servo/api.py#L283-L304
* https://github.com/opsani/servox/blob/896266cd2f68c13cb036b099f7806c8a44e9b6c3/servo/api.py#L267

**Comment by linkous8** [comment]
> As a general note - please test these changes before submitting a fix for review. If you need a way to simulate OCO responding with an error, see the original issue description (ENG-754), the issue is easily reproducible. If you want to have OCO return > 500 instead of 400 (for testing purposes), please see [this](https://github.com/opsani/oco/commit/4eef26fd8af2b2b945c8572361f4c433008b132b) OCO branch

As a general note, please attach FULL TRACE LEVEL logs when you expect someone to go fix something for you

**Review by pavel-georgiev — CHANGES_REQUESTED** [review]
@linkous8 As is, Servo still does not appear to log payload for >= 500 errors (as requested by ENG-790).

To avoid more cycles on this, please fix this and post sample output of how servo handles the errors (please test with 4xx and 5xx errors).

**Comment by DanielHHowell** [comment]
At risk of being too many cooks in the kitchen -- just trying to mediate here -- all that should be required to get this to the ticket specification is moving the payload logging from the giveup function to the main error block so it's caught no matter the status code.

**Comment by linkous8** [comment]
@DanielHHowell LGTM thank you :pray: 

@pavel-georgiev does this capture your completely unwritten requirements or will you require another half hour meeting to verbally communicate your concerns?

**Review by pavel-georgiev — APPROVED** [review]

**Pull request merged**
